version: '2'
services:
  eurekaserver:
    image: eureka-server:v1
    ports:
      - "8761:8761"
  configserver:
    image: configuration-server:v1
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
  zuulserver:
    image: zuul-server:v1
    ports:
      - "5555:5555"
    environment:
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:  "8761"
      CONFIGSERVER_PORT:  "8888"
  userservice:
    image: user-service:v1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
      AUTHSERVER_PORT:   "8091"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"
  orderservice:
    image: order-service:v1
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
      AUTHSERVER_PORT:   "8091"
      KAFKASERVER_PORT:    "2181"
  authenticationservice:
        image: authentication-service:v1
        ports:
          - "8901:8901"
        environment:
          SERVER_PORT: "8901"
          CONFIGSERVER_PORT: "8888"
          EUREKASERVER_PORT: "8761"
          CONFIGSERVER_URI: "http://configserver:8888"
          EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  redis:
      image: redis:alpine
      ports:
        - 6379:6379
  kafkaserver:
      image: spotify/kafka
      ports:
        - 2181:2181
        - 9092:9092