version: '2'
services:
  eurekaserver:
    image: eureka-server:v1
    ports:
      - "8761:8761"
  configserver:
    image: config-server:v1
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
  userservice:
    image: user-service:v1
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
  orderservice:
    image: order-service:v1
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: "8081"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"