server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/retr0spect/cloud-config-repo
          search-paths: user-service, order-service
          username:
          password:
      discovery:
        enabled: true
