security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orderChangeTopic
          content-type: application/json
          group: userGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost