server:
  port: 8082
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      uri: http://localhost:8888
