eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
       userInfoUri: http://localhost:8901/auth/user

spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  orderChangeTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.retrospect: DEBUG